with-expecter: true
dir: "{{.InterfaceDirRelative}}/mocks"
filename: "{{.InterfaceName | snakecase}}_mock.go"
mockname: "{{.InterfaceName}}Mock"
all: true
outpkg: "mocks"
packages:
  github.com/kylenguyen/wallet-app:
    config:
      recursive: true
