services:
  db:
    image: postgres:16.4
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234qwer
      POSTGRES_USER: postgres
      POSTGRES_DB: walletdb
    ports:
      - 5432:5432
    networks:
      - backend

  mysql_db:
    image: mysql:8.0 # Or your preferred MySQL version
    container_name: wallet-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer # Change this!
      MYSQL_DATABASE: walletdb
      # MYSQL_USER: user # Optional: if you want a non-root user
      # MYSQL_PASSWORD: userpassword # Optional: password for the non-root user
    ports:
      - 3306:3306
    networks:
      - backend
#  experiential-learning:
#    image: experiential-learning:v0.1
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - 4000:3000
#    depends_on:
#      - db
#    networks:
#      - backend
#    environment: # To connect with the database created by Docker Compose, and update URL to port 3000 to avoid conflict
#      DATABASE_URL: postgresql://postgres:felizznvd@db:5432/main-db
#      NEXTAUTH_URL: http://localhost:4000
#      APP_URL: http://localhost:4000

networks:
  backend:
    name: backend
    external: false