services:
  db:
    image: postgres:16.4
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234qwer
      POSTGRES_USER: postgres
      POSTGRES_DB: walletdb
    ports:
      - 5432:5432
    networks:
      - backend
#  experiential-learning:
#    image: experiential-learning:v0.1
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - 4000:3000
#    depends_on:
#      - db
#    networks:
#      - backend
#    environment: # To connect with the database created by Docker Compose, and update URL to port 3000 to avoid conflict
#      DATABASE_URL: postgresql://postgres:felizznvd@db:5432/main-db
#      NEXTAUTH_URL: http://localhost:4000
#      APP_URL: http://localhost:4000

networks:
  backend:
    name: backend
    external: false