// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	decimal "github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"

	model "bitbucket.org/ntuclink/ff-order-history-go/internal/model"
)

// WalletRepoMock is an autogenerated mock type for the WalletRepo type
type WalletRepoMock struct {
	mock.Mock
}

type WalletRepoMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WalletRepoMock) EXPECT() *WalletRepoMock_Expecter {
	return &WalletRepoMock_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function with given fields: ctx, userIDStr, walletIDStr, amount
func (_m *WalletRepoMock) Deposit(ctx context.Context, userIDStr string, walletIDStr string, amount decimal.Decimal) (*model.Transaction, error) {
	ret := _m.Called(ctx, userIDStr, walletIDStr, amount)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*model.Transaction, error)); ok {
		return rf(ctx, userIDStr, walletIDStr, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *model.Transaction); ok {
		r0 = rf(ctx, userIDStr, walletIDStr, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userIDStr, walletIDStr, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletRepoMock_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type WalletRepoMock_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDStr string
//   - walletIDStr string
//   - amount decimal.Decimal
func (_e *WalletRepoMock_Expecter) Deposit(ctx interface{}, userIDStr interface{}, walletIDStr interface{}, amount interface{}) *WalletRepoMock_Deposit_Call {
	return &WalletRepoMock_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userIDStr, walletIDStr, amount)}
}

func (_c *WalletRepoMock_Deposit_Call) Run(run func(ctx context.Context, userIDStr string, walletIDStr string, amount decimal.Decimal)) *WalletRepoMock_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *WalletRepoMock_Deposit_Call) Return(_a0 *model.Transaction, _a1 error) *WalletRepoMock_Deposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletRepoMock_Deposit_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*model.Transaction, error)) *WalletRepoMock_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionsByWalletID provides a mock function with given fields: ctx, userIDStr, walletIDStr
func (_m *WalletRepoMock) GetTransactionsByWalletID(ctx context.Context, userIDStr string, walletIDStr string) ([]model.Transaction, error) {
	ret := _m.Called(ctx, userIDStr, walletIDStr)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByWalletID")
	}

	var r0 []model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Transaction, error)); ok {
		return rf(ctx, userIDStr, walletIDStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Transaction); ok {
		r0 = rf(ctx, userIDStr, walletIDStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userIDStr, walletIDStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletRepoMock_GetTransactionsByWalletID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsByWalletID'
type WalletRepoMock_GetTransactionsByWalletID_Call struct {
	*mock.Call
}

// GetTransactionsByWalletID is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDStr string
//   - walletIDStr string
func (_e *WalletRepoMock_Expecter) GetTransactionsByWalletID(ctx interface{}, userIDStr interface{}, walletIDStr interface{}) *WalletRepoMock_GetTransactionsByWalletID_Call {
	return &WalletRepoMock_GetTransactionsByWalletID_Call{Call: _e.mock.On("GetTransactionsByWalletID", ctx, userIDStr, walletIDStr)}
}

func (_c *WalletRepoMock_GetTransactionsByWalletID_Call) Run(run func(ctx context.Context, userIDStr string, walletIDStr string)) *WalletRepoMock_GetTransactionsByWalletID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *WalletRepoMock_GetTransactionsByWalletID_Call) Return(_a0 []model.Transaction, _a1 error) *WalletRepoMock_GetTransactionsByWalletID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletRepoMock_GetTransactionsByWalletID_Call) RunAndReturn(run func(context.Context, string, string) ([]model.Transaction, error)) *WalletRepoMock_GetTransactionsByWalletID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWalletInfo provides a mock function with given fields: ctx, userId, walletId
func (_m *WalletRepoMock) GetWalletInfo(ctx context.Context, userId string, walletId string) (*model.Wallet, error) {
	ret := _m.Called(ctx, userId, walletId)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletInfo")
	}

	var r0 *model.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Wallet, error)); ok {
		return rf(ctx, userId, walletId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Wallet); ok {
		r0 = rf(ctx, userId, walletId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, walletId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletRepoMock_GetWalletInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWalletInfo'
type WalletRepoMock_GetWalletInfo_Call struct {
	*mock.Call
}

// GetWalletInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
//   - walletId string
func (_e *WalletRepoMock_Expecter) GetWalletInfo(ctx interface{}, userId interface{}, walletId interface{}) *WalletRepoMock_GetWalletInfo_Call {
	return &WalletRepoMock_GetWalletInfo_Call{Call: _e.mock.On("GetWalletInfo", ctx, userId, walletId)}
}

func (_c *WalletRepoMock_GetWalletInfo_Call) Run(run func(ctx context.Context, userId string, walletId string)) *WalletRepoMock_GetWalletInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *WalletRepoMock_GetWalletInfo_Call) Return(_a0 *model.Wallet, _a1 error) *WalletRepoMock_GetWalletInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletRepoMock_GetWalletInfo_Call) RunAndReturn(run func(context.Context, string, string) (*model.Wallet, error)) *WalletRepoMock_GetWalletInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Transfer provides a mock function with given fields: ctx, sourceUserIDStr, sourceWalletIDStr, destinationWalletIDStr, amount
func (_m *WalletRepoMock) Transfer(ctx context.Context, sourceUserIDStr string, sourceWalletIDStr string, destinationWalletIDStr string, amount decimal.Decimal) (*model.Transaction, error) {
	ret := _m.Called(ctx, sourceUserIDStr, sourceWalletIDStr, destinationWalletIDStr, amount)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, decimal.Decimal) (*model.Transaction, error)); ok {
		return rf(ctx, sourceUserIDStr, sourceWalletIDStr, destinationWalletIDStr, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, decimal.Decimal) *model.Transaction); ok {
		r0 = rf(ctx, sourceUserIDStr, sourceWalletIDStr, destinationWalletIDStr, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, sourceUserIDStr, sourceWalletIDStr, destinationWalletIDStr, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletRepoMock_Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transfer'
type WalletRepoMock_Transfer_Call struct {
	*mock.Call
}

// Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceUserIDStr string
//   - sourceWalletIDStr string
//   - destinationWalletIDStr string
//   - amount decimal.Decimal
func (_e *WalletRepoMock_Expecter) Transfer(ctx interface{}, sourceUserIDStr interface{}, sourceWalletIDStr interface{}, destinationWalletIDStr interface{}, amount interface{}) *WalletRepoMock_Transfer_Call {
	return &WalletRepoMock_Transfer_Call{Call: _e.mock.On("Transfer", ctx, sourceUserIDStr, sourceWalletIDStr, destinationWalletIDStr, amount)}
}

func (_c *WalletRepoMock_Transfer_Call) Run(run func(ctx context.Context, sourceUserIDStr string, sourceWalletIDStr string, destinationWalletIDStr string, amount decimal.Decimal)) *WalletRepoMock_Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(decimal.Decimal))
	})
	return _c
}

func (_c *WalletRepoMock_Transfer_Call) Return(_a0 *model.Transaction, _a1 error) *WalletRepoMock_Transfer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletRepoMock_Transfer_Call) RunAndReturn(run func(context.Context, string, string, string, decimal.Decimal) (*model.Transaction, error)) *WalletRepoMock_Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userIDStr, walletIDStr, amount
func (_m *WalletRepoMock) Withdraw(ctx context.Context, userIDStr string, walletIDStr string, amount decimal.Decimal) (*model.Transaction, error) {
	ret := _m.Called(ctx, userIDStr, walletIDStr, amount)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) (*model.Transaction, error)); ok {
		return rf(ctx, userIDStr, walletIDStr, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, decimal.Decimal) *model.Transaction); ok {
		r0 = rf(ctx, userIDStr, walletIDStr, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, decimal.Decimal) error); ok {
		r1 = rf(ctx, userIDStr, walletIDStr, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WalletRepoMock_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type WalletRepoMock_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDStr string
//   - walletIDStr string
//   - amount decimal.Decimal
func (_e *WalletRepoMock_Expecter) Withdraw(ctx interface{}, userIDStr interface{}, walletIDStr interface{}, amount interface{}) *WalletRepoMock_Withdraw_Call {
	return &WalletRepoMock_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userIDStr, walletIDStr, amount)}
}

func (_c *WalletRepoMock_Withdraw_Call) Run(run func(ctx context.Context, userIDStr string, walletIDStr string, amount decimal.Decimal)) *WalletRepoMock_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(decimal.Decimal))
	})
	return _c
}

func (_c *WalletRepoMock_Withdraw_Call) Return(_a0 *model.Transaction, _a1 error) *WalletRepoMock_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WalletRepoMock_Withdraw_Call) RunAndReturn(run func(context.Context, string, string, decimal.Decimal) (*model.Transaction, error)) *WalletRepoMock_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewWalletRepoMock creates a new instance of WalletRepoMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepoMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepoMock {
	mock := &WalletRepoMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
